In [1]:
import torch
from my_utils import CustomCocoDataset, get_transform, get_model_instance_segmentation

import torchvision
from torchvision.io import read_image
from torchvision.io import ImageReadMode
from torchvision.transforms import v2

device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

num_classes = 91 + 1  # including background

# model = get_model_instance_segmentation(num_classes)
model = torchvision.models.detection.maskrcnn_resnet50_fpn(weights="DEFAULT")
model.to(device)
model.eval()


MaskRCNN(
  (transform): GeneralizedRCNNTransform(
      Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
      Resize(min_size=(800,), max_size=1333, mode='bilinear')
  )
  (backbone): BackboneWithFPN(
    (body): IntermediateLayerGetter(
      (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
      (bn1): FrozenBatchNorm2d(64, eps=0.0)
      (relu): ReLU(inplace=True)
      (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
      (layer1): Sequential(
        (0): Bottleneck(
          (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): FrozenBatchNorm2d(64, eps=0.0)
          (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): FrozenBatchNorm2d(64, eps=0.0)
          (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): FrozenBatchNorm2d(256, eps=0.0)
          (relu): ReLU(in

In [2]:

x = [torch.rand(3, 300, 400), torch.rand(3, 500, 400)]
output = model(x)
print(type(output))
print(len(output))
output[0]

<class 'list'>
2


{'boxes': tensor([], size=(0, 4), grad_fn=<StackBackward0>),
 'labels': tensor([], dtype=torch.int64),
 'scores': tensor([], grad_fn=<IndexBackward0>),
 'masks': tensor([], size=(0, 1, 300, 400))}

In [3]:
output[1]

{'boxes': tensor([], size=(0, 4), grad_fn=<StackBackward0>),
 'labels': tensor([], dtype=torch.int64),
 'scores': tensor([], grad_fn=<IndexBackward0>),
 'masks': tensor([], size=(0, 1, 500, 400))}

In [4]:
type(output[0])

dict

In [5]:
output[0].keys()

dict_keys(['boxes', 'labels', 'scores', 'masks'])

In [6]:
out = output[0]
type(out["masks"])

torch.Tensor

In [7]:
out["masks"].shape

torch.Size([0, 1, 300, 400])

In [8]:
image = read_image('../data/images/000000000785.jpg', ImageReadMode.RGB)
image = v2.functional.convert_image_dtype(image, dtype=torch.float)
images = [image]

In [9]:
(type(image.dtype))

torch.dtype

In [10]:
image.shape

torch.Size([3, 425, 640])

In [11]:
predictions = model(images)

In [12]:
predictions

[{'boxes': tensor([[278.5533,  47.6177, 496.1945, 383.7493],
          [192.7853, 363.9044, 609.4540, 398.7617],
          [209.7503, 358.2017, 518.1153, 385.6756],
          [253.2186, 377.1271, 619.0859, 400.9147],
          [211.8557, 365.5201, 454.6290, 394.2666],
          [426.3409, 383.4187, 612.0369, 394.3759],
          [459.7468,  57.6889, 463.0028,  62.6333],
          [311.6180, 366.2035, 444.0308, 379.2382],
          [633.2665,  61.7603, 636.7625,  66.8119],
          [209.0767, 366.9852, 439.1762, 380.3322],
          [194.8698, 331.1051, 606.3942, 396.5959],
          [ 12.3815,  64.5463,  15.4442,  68.1231],
          [262.7417, 381.4393, 422.0511, 399.4939],
          [298.4577, 349.8089, 556.9088, 406.5624]], grad_fn=<StackBackward0>),
  'labels': tensor([ 1, 35, 35, 35, 35, 35,  1, 35, 10, 35, 35, 38, 35, 35]),
  'scores': tensor([0.9998, 0.9573, 0.7197, 0.5557, 0.5496, 0.2480, 0.1632, 0.1399, 0.1336,
          0.1278, 0.1031, 0.0752, 0.0734, 0.0524], grad_fn=<Index

In [13]:
predictions[0]

{'boxes': tensor([[278.5533,  47.6177, 496.1945, 383.7493],
         [192.7853, 363.9044, 609.4540, 398.7617],
         [209.7503, 358.2017, 518.1153, 385.6756],
         [253.2186, 377.1271, 619.0859, 400.9147],
         [211.8557, 365.5201, 454.6290, 394.2666],
         [426.3409, 383.4187, 612.0369, 394.3759],
         [459.7468,  57.6889, 463.0028,  62.6333],
         [311.6180, 366.2035, 444.0308, 379.2382],
         [633.2665,  61.7603, 636.7625,  66.8119],
         [209.0767, 366.9852, 439.1762, 380.3322],
         [194.8698, 331.1051, 606.3942, 396.5959],
         [ 12.3815,  64.5463,  15.4442,  68.1231],
         [262.7417, 381.4393, 422.0511, 399.4939],
         [298.4577, 349.8089, 556.9088, 406.5624]], grad_fn=<StackBackward0>),
 'labels': tensor([ 1, 35, 35, 35, 35, 35,  1, 35, 10, 35, 35, 38, 35, 35]),
 'scores': tensor([0.9998, 0.9573, 0.7197, 0.5557, 0.5496, 0.2480, 0.1632, 0.1399, 0.1336,
         0.1278, 0.1031, 0.0752, 0.0734, 0.0524], grad_fn=<IndexBackward0>),
 'ma

In [14]:
out = predictions[0]

In [15]:
out["masks"].shape

torch.Size([14, 1, 425, 640])

In [18]:
out["scores"].shape

torch.Size([14])

In [19]:
out["labels"].shape

torch.Size([14])

In [20]:
out["boxes"].shape

torch.Size([14, 4])

In [22]:
mask = out["masks"]
mask[0].shape

torch.Size([1, 425, 640])

In [24]:
mask[0][0].shape

torch.Size([425, 640])

In [25]:
mask[0]

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], grad_fn=<SelectBackward0>)

In [26]:
reshaped_mask = mask.reshape(-1, 425, 640)
reshaped_mask.shape

torch.Size([14, 425, 640])

In [27]:
# 1つ目の画像のマスク
reshaped_mask[0]

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], grad_fn=<SelectBackward0>)

In [32]:

torch.unique(reshaped_mask[0], return_counts=True)

(tensor([0.0000e+00, 6.6828e-07, 9.8776e-07,  ..., 9.9988e-01, 9.9988e-01,
         9.9988e-01], grad_fn=<Unique2Backward0>),
 tensor([193126,      1,      1,  ...,      1,      1,      1]))

In [36]:
reshaped_mask[0][reshaped_mask[0] >= 0.5]

tensor([0.5103, 0.5106, 0.5109,  ..., 0.5302, 0.5196, 0.5091],
       grad_fn=<IndexBackward0>)

In [37]:
torch.unique(reshaped_mask[0][reshaped_mask[0] >= 0.5], return_counts=True)

(tensor([0.5000, 0.5000, 0.5001,  ..., 0.9999, 0.9999, 0.9999],
        grad_fn=<Unique2Backward0>),
 tensor([1, 1, 1,  ..., 1, 1, 1]))

In [38]:
# 3次元のtensorを適当に作成
a = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
a

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [39]:
a > 2

tensor([[[False, False,  True],
         [ True,  True,  True]],

        [[ True,  True,  True],
         [ True,  True,  True]]])

In [40]:
a[a > 2]

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])